// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1mApaBygQOVWo2_IA2nqwp3xTPCKty0',
    appId: '1:821098579291:web:430446aa86c5ea43a4467e',
    messagingSenderId: '821098579291',
    projectId: 'instagram-clone-33572',
    authDomain: 'instagram-clone-33572.firebaseapp.com',
    storageBucket: 'instagram-clone-33572.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_HrTnBkMWp2OuYCZFJP-y3Q2UPTzid0',
    appId: '1:821098579291:android:11d17255f78ead76a4467e',
    messagingSenderId: '821098579291',
    projectId: 'instagram-clone-33572',
    storageBucket: 'instagram-clone-33572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXp0_hIQAzmwPj3Nm2i_QgSh2hD70tYBw',
    appId: '1:821098579291:ios:3265fd0724e20783a4467e',
    messagingSenderId: '821098579291',
    projectId: 'instagram-clone-33572',
    storageBucket: 'instagram-clone-33572.appspot.com',
    iosClientId: '821098579291-fmgc9f1p63eg0d6sb9t7jvioma2n1lu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXp0_hIQAzmwPj3Nm2i_QgSh2hD70tYBw',
    appId: '1:821098579291:ios:3265fd0724e20783a4467e',
    messagingSenderId: '821098579291',
    projectId: 'instagram-clone-33572',
    storageBucket: 'instagram-clone-33572.appspot.com',
    iosClientId: '821098579291-fmgc9f1p63eg0d6sb9t7jvioma2n1lu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
